defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: aureliavnext/circleci:0.0.3

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - run:
          name: "Show npm and node versions"
          command: |
            node --version
            npm --version
      - checkout
      - run: npm ci -dd
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  unit_tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: mkdir ~/repo/junit
      - run:
          command: "npm run test"
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
          when: always
      - store_test_results:
          path: ~/repo/junit
      - store_artifacts:
          path: ./junit

workflows:
    version: 2
    install_and_test:
        jobs:
            - install
            - unit_tests:
                requires:
                    - install
