# Defaults for all jobs

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: aureliavnext/circleci:0.0.6

# Variables
var_1: &cache_key aurelia-{{ .Branch }}-{{ checksum "package-lock.json" }}

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - run:
          name: "Show npm and node versions"
          command: |
            node --version
            npm --version
      - checkout
      - run: npm ci -dd
      - save_cache:
          key: *cache_key
          paths:
            - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: au build
      - persist_to_workspace:
          root: ~/repo
          path: ./scripts

  unit_tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: mkdir ~/repo/junit
      - run:
          command: "npm run test"
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
      - run: codecov
      - store_test_results:
          path: ~/repo/junit
      - store_artifacts:
          path: ./junit
      - store_artifacts:
          path: ./coverage

workflows:
    version: 2
    default_workflow:
        jobs:
            - install
            - build:
                requires:
                    - install
            - unit_tests:
                requires:
                    - install
